# Generated by Django 4.2.26 on 2025-11-27 18:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur')], default='user', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=150)),
                ('total', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=340)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_commande', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_whatsapp', models.CharField(default='+257 69 08 02 78', max_length=20)),
                ('email', models.EmailField(default='karinzi.bi.sab@gmail.com', max_length=254)),
                ('adresse', models.CharField(default='Bujumbura - Burundi, bldg Saint Pierre Avenue de l’OUA', max_length=255)),
            ],
            options={
                'verbose_name': 'Information de contact',
                'verbose_name_plural': 'Informations de contact',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='voitures.marque')),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'ordering': ['nom'],
                'unique_together': {('marque', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chassis', models.CharField(max_length=100, unique=True)),
                ('numero_moteur', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique'), ('Autre', 'Autre')], max_length=20)),
                ('kilometrage', models.FloatField(help_text='Distance parcourue en kilomètres')),
                ('couleur', models.CharField(max_length=50)),
                ('cylindree_cc', models.PositiveIntegerField(verbose_name='Cylindrée (CC)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos')),
                ('etat', models.CharField(choices=[('Disponible', 'Disponible'), ('Réservée', 'Réservée'), ('Vendue', 'Vendue')], default='Disponible', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='voitures.marque')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='voitures.modele')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='voitures.voiture')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
    ]
