# Generated by Django 4.2.26 on 2026-01-02 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse email"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nom d'utilisateur"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Administrateur"), ("user", "Utilisateur")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telephone_whatsapp",
                    models.CharField(default="+257 69 08 02 78", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        default="karinzi.bi.sab@gmail.com", max_length=254
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        default="Bujumbura - Burundi, bldg Saint Pierre Avenue de l’OUA",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Information de contact",
                "verbose_name_plural": "Informations de contact",
            },
        ),
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("logo", models.FileField(blank=True, null=True, upload_to="logos")),
            ],
            options={
                "verbose_name": "Marque",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Modele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="modeles"),
                ),
                (
                    "marque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modeles",
                        to="voitures.marque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle",
                "verbose_name_plural": "Modèles",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_chassis", models.CharField(max_length=100, unique=True)),
                ("numero_moteur", models.CharField(max_length=100)),
                ("annee", models.PositiveIntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("Manuelle", "Manuelle"),
                            ("Automatique", "Automatique"),
                            ("Autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kilometrage",
                    models.FloatField(help_text="Distance parcourue en kilomètres"),
                ),
                ("couleur", models.CharField(max_length=50)),
                (
                    "cylindree_cc",
                    models.PositiveIntegerField(verbose_name="Cylindrée (CC)"),
                ),
                ("prix", models.DecimalField(decimal_places=2, max_digits=12)),
                ("photo", models.FileField(blank=True, null=True, upload_to="photos")),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("Réservée", "Réservée"),
                            ("Vendue", "Vendue"),
                        ],
                        default="Disponible",
                        max_length=20,
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "marque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voitures",
                        to="voitures.marque",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voitures",
                        to="voitures.modele",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voiture",
                "verbose_name_plural": "Voitures",
                "ordering": ["-date_ajout"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reservation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voiture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to="voitures.voiture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="voitures_supplementaires/")),
                (
                    "voiture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="voitures.voiture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image supplémentaire",
                "verbose_name_plural": "Images supplémentaires",
            },
        ),
        migrations.AddConstraint(
            model_name="modele",
            constraint=models.UniqueConstraint(
                fields=("marque", "nom"), name="unique_marque_nom"
            ),
        ),
    ]
