# Generated by Django 5.2.8 on 2025-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='voiture',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
