# Generated by Django 4.2.26 on 2025-11-30 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voitures", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={},
        ),
        migrations.AlterField(
            model_name="reservation",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="voiture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="voitures.voiture"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("voiture",), name="unique_voiture_active"
            ),
        ),
    ]
