# Generated by Django 4.2.26 on 2025-12-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voiture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voitures.voiture'),
        ),
    ]
