# Generated by Django 4.2.26 on 2025-12-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0003_alter_customuser_email_alter_reservation_voiture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
