# Generated by Django 4.2.26 on 2025-12-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos'),
        ),
    ]
