# Generated by Django 4.2.26 on 2025-12-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0005_marque_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.CreateModel(
            name='VoitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='voitures/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='voitures.voiture')),
            ],
        ),
    ]
