# Generated by Django 4.2.26 on 2025-12-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0006_alter_voiture_photo_voitureimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.DeleteModel(
            name='VoitureImage',
        ),
    ]
