# Generated by Django 4.2.26 on 2025-12-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0007_alter_voiture_photo_delete_voitureimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='voitures_supplementaires/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='voitures.voiture')),
            ],
            options={
                'verbose_name': 'Image supplémentaire',
                'verbose_name_plural': 'Images supplémentaires',
            },
        ),
    ]
