# Generated by Django 4.2.26 on 2025-12-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0008_voitureimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voitureimage',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='voitureimage',
            name='description',
        ),
    ]
