# Generated by Django 4.2.26 on 2025-12-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0009_rename_image_voitureimage_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoitureImage',
            new_name='Image',
        ),
    ]
