# Generated by Django 4.2.26 on 2025-12-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0010_rename_voitureimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
