# Generated by Django 4.2.26 on 2025-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0011_rename_images_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, help_text="Description de l'image", max_length=255, null=True, verbose_name='Description'),
        ),
    ]
