# Generated by Django 4.2.26 on 2025-12-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0012_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
